<template>
  <div class="space-y-5">
    <PageHeader
      eyebrow="Task Create"
      title="Create Task"
      description="The task stores business context. The profile controls packaging, parsing, archiving, and playback rules."
      :meta="headerMeta"
    >
      <template #actions>
        <BaseButton to="/tasks">Back to Tasks</BaseButton>
      </template>
    </PageHeader>

    <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]">
      <PageCard eyebrow="Basics" title="Task Info" description="Pick a profile first, then derive device and modality from it.">
        <form class="grid gap-4 md:grid-cols-2" @submit.prevent="handleSubmit">
          <label class="block">
            <span class="mb-1.5 block text-sm font-medium text-slate-700">Task Name</span>
            <input v-model="form.taskName" required class="app-input" placeholder="e.g. gait-batch-02" />
          </label>
          <label class="block">
            <span class="mb-1.5 block text-sm font-medium text-slate-700">Operator</span>
            <input v-model="form.operatorName" class="app-input" placeholder="e.g. operator-a" />
          </label>
          <label class="block">
            <span class="mb-1.5 block text-sm font-medium text-slate-700">Collect Date</span>
            <input v-model="form.collectDate" type="date" required class="app-input" />
          </label>
          <label class="block md:col-span-2">
            <span class="mb-1.5 block text-sm font-medium text-slate-700">Collection Profile</span>
            <select v-model="profileIdValue" required class="app-input">
              <option :value="''" disabled>Select a profile</option>
              <option v-for="profile in profiles" :key="profile.id" :value="String(profile.id)">
                {{ profile.profileName }} ({{ profile.profileCode }})
              </option>
            </select>
          </label>
          <label class="block">
            <span class="mb-1.5 block text-sm font-medium text-slate-700">Device Group</span>
            <input :value="selectedProfile?.deviceGroupCode || ''" readonly class="app-input bg-slate-50 text-slate-500" placeholder="derived from profile" />
          </label>
          <label class="block">
            <span class="mb-1.5 block text-sm font-medium text-slate-700">Modality Group</span>
            <input :value="selectedProfile?.modalityGroupCode || ''" readonly class="app-input bg-slate-50 text-slate-500" placeholder="derived from profile" />
          </label>
          <label class="block md:col-span-2">
            <span class="mb-1.5 block text-sm font-medium text-slate-700">Capture Location</span>
            <input v-model="form.captureLocation" class="app-input" placeholder="e.g. lab-a / motion-zone-1" />
          </label>
          <label class="block md:col-span-2">
            <span class="mb-1.5 block text-sm font-medium text-slate-700">Scene</span>
            <input v-model="form.scene" class="app-input" placeholder="optional" />
          </label>
          <label class="block md:col-span-2">
            <span class="mb-1.5 block text-sm font-medium text-slate-700">Remark</span>
            <textarea v-model="form.remark" rows="4" class="app-input resize-y" placeholder="task context"></textarea>
          </label>

          <div class="flex items-center gap-3 md:col-span-2">
            <BaseButton variant="primary" type="submit" :disabled="submitting || loadingProfiles">
              {{ submitting ? "Creating..." : "Create Task" }}
            </BaseButton>
            <span v-if="errorMessage" class="text-xs text-rose-700">{{ errorMessage }}</span>
          </div>
        </form>
      </PageCard>

      <PageCard
        eyebrow="Rules"
        title="Profile Notes"
        description="Add new profiles and resolver implementations for new multimodal combinations instead of expanding task fields."
        secondary
      >
        <ul class="space-y-3 text-xs leading-5 text-slate-500">
          <li>One profile maps to one end-to-end collection rule set.</li>
          <li>The task page stores business context only.</li>
          <li>Subject code can be blank and will be generated by the backend.</li>
          <li>Device and modality are display-only to keep rules consistent.</li>
        </ul>
      </PageCard>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { useRouter } from "vue-router";
import { fetchCollectionProfiles, type CollectionProfileResponse } from "@/api/profiles";
import { createTask } from "@/api/tasks";
import BaseButton from "@/components/BaseButton.vue";
import PageCard from "@/components/PageCard.vue";
import PageHeader from "@/components/PageHeader.vue";
import type { CreateTaskRequest } from "@/types/task";

const router = useRouter();
const submitting = ref(false);
const loadingProfiles = ref(false);
const errorMessage = ref("");
const profiles = ref<CollectionProfileResponse[]>([]);
const profileIdValue = ref("");

const form = reactive<CreateTaskRequest>({
  taskName: "",
  profileId: null,
  deviceType: "",
  modality: "",
  collectDate: "",
  scene: "",
  operatorName: "",
  captureLocation: "",
  remark: ""
});

const selectedProfile = computed(() => profiles.value.find((profile) => String(profile.id) === profileIdValue.value) ?? null);

const headerMeta = computed(() => [
  { label: "Profile", value: selectedProfile.value?.profileCode || "not selected" },
  { label: "Device", value: selectedProfile.value?.deviceGroupCode || "-" },
  { label: "Modality", value: selectedProfile.value?.modalityGroupCode || "-" }
]);

async function loadProfiles() {
  loadingProfiles.value = true;
  try {
    profiles.value = await fetchCollectionProfiles();
    if (profiles.value.length > 0) {
      profileIdValue.value = String(profiles.value[0].id);
    }
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Failed to load profiles";
  } finally {
    loadingProfiles.value = false;
  }
}

async function handleSubmit() {
  if (!selectedProfile.value) {
    errorMessage.value = "Please select a profile";
    return;
  }
  submitting.value = true;
  errorMessage.value = "";
  try {
    form.profileId = selectedProfile.value.id;
    form.deviceType = selectedProfile.value.deviceGroupCode;
    form.modality = selectedProfile.value.modalityGroupCode;
    const task = await createTask(form);
    await router.push(`/tasks/${task.id}`);
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Failed to create task";
  } finally {
    submitting.value = false;
  }
}

onMounted(loadProfiles);
</script>
