server:
  port: 19021

spring:
  application:
    name: mmdp-backend
  datasource:
    url: jdbc:mysql://100.120.105.120:13306/mmdp_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

minio:
  endpoint: http://100.120.105.120:29010
  access-key: admin
  secret-key: 123123123
  bucket: mmdp-test
