CREATE TABLE IF NOT EXISTS subject (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '被试主键ID',
    subject_code VARCHAR(64) NOT NULL COMMENT '平台被试编号',
    subject_name VARCHAR(128) NULL COMMENT '被试名称',
    gender VARCHAR(16) NULL COMMENT '性别',
    age INT NULL COMMENT '年龄',
    note VARCHAR(512) NULL COMMENT '备注',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    UNIQUE INDEX uk_subject_code (subject_code)
) COMMENT='被试主表';

CREATE TABLE IF NOT EXISTS collector_client (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '采集端主键ID',
    client_code VARCHAR(64) NOT NULL COMMENT '采集端编号',
    client_name VARCHAR(128) NOT NULL COMMENT '采集端名称',
    location VARCHAR(255) NULL COMMENT '采集端位置',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态',
    remark VARCHAR(512) NULL COMMENT '备注',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    UNIQUE INDEX uk_collector_client_code (client_code)
) COMMENT='采集端主表';

CREATE TABLE IF NOT EXISTS collection_profile (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '采集Profile主键ID',
    profile_code VARCHAR(64) NOT NULL COMMENT 'Profile编码',
    profile_name VARCHAR(128) NOT NULL COMMENT 'Profile名称',
    task_type_code VARCHAR(64) NOT NULL COMMENT '任务类型编码',
    modality_group_code VARCHAR(64) NOT NULL COMMENT '模态组合编码',
    device_group_code VARCHAR(64) NOT NULL COMMENT '设备组合编码',
    package_rule_code VARCHAR(64) NOT NULL COMMENT '打包规则编码',
    parser_rule_code VARCHAR(64) NOT NULL COMMENT '解析规则编码',
    archive_rule_code VARCHAR(64) NOT NULL COMMENT '归档规则编码',
    playback_rule_code VARCHAR(64) NOT NULL COMMENT '回放规则编码',
    version VARCHAR(32) NOT NULL DEFAULT 'v1' COMMENT '版本号',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    remark VARCHAR(512) NULL COMMENT '备注',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    UNIQUE INDEX uk_collection_profile_code (profile_code)
) COMMENT='采集Profile主表';

CREATE TABLE IF NOT EXISTS collection_profile_source (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Profile source主键ID',
    profile_id BIGINT NOT NULL COMMENT '关联Profile ID',
    source_key VARCHAR(64) NOT NULL COMMENT 'source键',
    source_name VARCHAR(128) NOT NULL COMMENT 'source名称',
    source_type VARCHAR(32) NOT NULL COMMENT 'source类型',
    device_role_code VARCHAR(64) NULL COMMENT '设备角色编码',
    required_flag TINYINT NOT NULL DEFAULT 1 COMMENT '是否必需',
    file_pattern VARCHAR(255) NULL COMMENT '文件匹配模式',
    parsed_asset_type VARCHAR(64) NOT NULL COMMENT '解析后资产类型',
    playback_kind VARCHAR(32) NULL COMMENT '回放类型',
    expected_fps DECIMAL(10, 2) NULL COMMENT '期望帧率',
    expected_sample_rate DECIMAL(10, 2) NULL COMMENT '期望采样率',
    sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    CONSTRAINT fk_profile_source_profile FOREIGN KEY (profile_id) REFERENCES collection_profile(id),
    UNIQUE INDEX uk_profile_source_key (profile_id, source_key)
) COMMENT='采集Profile source定义表';

CREATE TABLE IF NOT EXISTS acquisition_task (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '采集任务主键ID',
    task_code VARCHAR(64) NOT NULL COMMENT '平台任务编号',
    task_name VARCHAR(128) NOT NULL COMMENT '采集任务名称',
    subject_id BIGINT NULL COMMENT '关联被试ID',
    subject_code VARCHAR(64) NOT NULL COMMENT '兼容字段：被试编号',
    subject_code_snapshot VARCHAR(64) NULL COMMENT '被试编号快照',
    action_name VARCHAR(128) NOT NULL COMMENT '采集动作名称',
    device_type VARCHAR(64) NOT NULL COMMENT '兼容字段：采集设备类型',
    modality VARCHAR(32) NOT NULL COMMENT '兼容字段：数据模态类型',
    collect_date DATE NOT NULL COMMENT '采集日期',
    scene VARCHAR(128) NULL COMMENT '采集场景',
    operator_name VARCHAR(128) NULL COMMENT '采集人员',
    capture_location VARCHAR(255) NULL COMMENT '采集地点',
    profile_id BIGINT NULL COMMENT '关联采集Profile ID',
    task_source VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '任务来源',
    collector_client_id BIGINT NULL COMMENT '关联采集端ID',
    status VARCHAR(32) NOT NULL COMMENT '任务状态',
    remark VARCHAR(512) NULL COMMENT '任务备注',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    CONSTRAINT fk_task_subject FOREIGN KEY (subject_id) REFERENCES subject(id),
    CONSTRAINT fk_task_profile FOREIGN KEY (profile_id) REFERENCES collection_profile(id),
    CONSTRAINT fk_task_collector_client FOREIGN KEY (collector_client_id) REFERENCES collector_client(id),
    UNIQUE INDEX uk_task_code (task_code),
    INDEX idx_task_subject_id (subject_id),
    INDEX idx_task_profile_id (profile_id),
    INDEX idx_task_collector_client_id (collector_client_id)
) COMMENT='采集任务主表';

CREATE TABLE IF NOT EXISTS collection_session (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '采集Session主键ID',
    session_code VARCHAR(64) NOT NULL COMMENT '平台Session编号',
    task_id BIGINT NOT NULL COMMENT '关联采集任务ID',
    subject_id BIGINT NULL COMMENT '关联被试ID',
    session_id VARCHAR(128) NOT NULL COMMENT '兼容字段：Session标识',
    local_task_id VARCHAR(64) NULL COMMENT '采集端本地任务ID',
    subject_code VARCHAR(64) NOT NULL COMMENT '兼容字段：被试编号',
    subject_code_snapshot VARCHAR(64) NULL COMMENT '被试编号快照',
    action_name VARCHAR(128) NOT NULL COMMENT '兼容字段：动作名称',
    action_name_snapshot VARCHAR(128) NULL COMMENT '动作名快照',
    profile_id BIGINT NULL COMMENT '关联采集Profile ID',
    collector_client_id BIGINT NULL COMMENT '关联采集端ID',
    started_at DATETIME NOT NULL COMMENT '开始时间',
    ended_at DATETIME NULL COMMENT '结束时间',
    duration_ms BIGINT NULL COMMENT '时长毫秒',
    timestamp_policy VARCHAR(64) NULL COMMENT '时间戳策略',
    manifest_json TEXT NOT NULL COMMENT 'Session manifest JSON',
    upload_status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED' COMMENT '上传状态',
    session_status VARCHAR(32) NOT NULL DEFAULT 'IMPORTED' COMMENT 'Session状态',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    updated_at DATETIME NULL COMMENT '更新时间',
    CONSTRAINT fk_session_task FOREIGN KEY (task_id) REFERENCES acquisition_task(id),
    CONSTRAINT fk_session_subject FOREIGN KEY (subject_id) REFERENCES subject(id),
    CONSTRAINT fk_session_profile FOREIGN KEY (profile_id) REFERENCES collection_profile(id),
    CONSTRAINT fk_session_collector_client FOREIGN KEY (collector_client_id) REFERENCES collector_client(id),
    UNIQUE INDEX uk_session_code (session_code),
    UNIQUE INDEX idx_session_id (session_id),
    INDEX idx_session_task_id (task_id),
    INDEX idx_session_profile_id (profile_id),
    INDEX idx_session_collector_client_id (collector_client_id)
) COMMENT='采集Session主表';

CREATE TABLE IF NOT EXISTS data_file (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '数据文件主键ID',
    task_id BIGINT NOT NULL COMMENT '关联采集任务ID',
    session_id BIGINT NULL COMMENT '关联Session记录ID',
    file_role VARCHAR(64) NULL COMMENT '文件角色',
    source_key VARCHAR(64) NULL COMMENT 'source键',
    original_filename VARCHAR(255) NOT NULL COMMENT '原始文件名',
    relative_path VARCHAR(255) NULL COMMENT '归档包内相对路径',
    file_ext VARCHAR(32) NOT NULL COMMENT '文件扩展名',
    content_type VARCHAR(128) NOT NULL COMMENT 'MIME类型',
    file_size BIGINT NOT NULL COMMENT '文件大小',
    sha256 VARCHAR(64) NULL COMMENT '文件哈希',
    asset_type VARCHAR(64) NULL COMMENT '资产类型提示',
    storage_provider VARCHAR(32) NOT NULL DEFAULT 'OSS' COMMENT 'storage provider',
    bucket_name VARCHAR(128) NOT NULL COMMENT '对象存储桶名',
    object_key VARCHAR(255) NOT NULL COMMENT '对象存储key',
    storage_url VARCHAR(512) NOT NULL COMMENT '存储访问地址',
    upload_status VARCHAR(32) NOT NULL COMMENT '上传状态',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    CONSTRAINT fk_data_file_task FOREIGN KEY (task_id) REFERENCES acquisition_task(id),
    CONSTRAINT fk_data_file_session FOREIGN KEY (session_id) REFERENCES collection_session(id),
    INDEX idx_data_file_session_id (session_id),
    INDEX idx_data_file_source_key (source_key),
    INDEX idx_data_file_sha256 (sha256)
) COMMENT='数据文件主表';

CREATE TABLE IF NOT EXISTS qc_report (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '质检报告主键ID',
    task_id BIGINT NOT NULL COMMENT '关联采集任务ID',
    session_id BIGINT NULL COMMENT '关联Session记录ID',
    file_id BIGINT NOT NULL COMMENT '关联数据文件ID',
    qc_type VARCHAR(32) NOT NULL DEFAULT 'FILE' COMMENT '质检类型：FILE=单文件，SESSION=跨文件',
    qc_status VARCHAR(32) NOT NULL COMMENT '质检状态',
    summary VARCHAR(512) NOT NULL COMMENT '质检摘要',
    report_json TEXT NOT NULL COMMENT '质检报告JSON',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    CONSTRAINT fk_qc_report_task FOREIGN KEY (task_id) REFERENCES acquisition_task(id),
    CONSTRAINT fk_qc_report_session FOREIGN KEY (session_id) REFERENCES collection_session(id),
    CONSTRAINT fk_qc_report_file FOREIGN KEY (file_id) REFERENCES data_file(id),
    INDEX idx_qc_report_session_id (session_id)
) COMMENT='质检报告表';

CREATE TABLE IF NOT EXISTS processing_job (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '处理作业主键ID',
    task_id BIGINT NOT NULL COMMENT '关联采集任务ID',
    session_id BIGINT NULL COMMENT '关联Session记录ID',
    pipeline_id VARCHAR(64) NOT NULL COMMENT '处理流程ID',
    executor_type VARCHAR(32) NOT NULL COMMENT '执行器类型',
    status VARCHAR(32) NOT NULL COMMENT '作业状态',
    parameters_json TEXT NULL COMMENT '作业参数JSON',
    params_json TEXT NULL COMMENT '兼容字段：作业参数JSON',
    result_json TEXT NULL COMMENT '结果JSON',
    error_message VARCHAR(512) NULL COMMENT '错误信息',
    operator_name VARCHAR(128) NULL COMMENT '操作人员',
    tool_name VARCHAR(128) NULL COMMENT '工具名称',
    tool_version VARCHAR(64) NULL COMMENT '工具版本',
    log_path VARCHAR(512) NULL COMMENT '日志路径',
    remark VARCHAR(512) NULL COMMENT '备注',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    CONSTRAINT fk_processing_job_task FOREIGN KEY (task_id) REFERENCES acquisition_task(id),
    CONSTRAINT fk_processing_job_session FOREIGN KEY (session_id) REFERENCES collection_session(id),
    INDEX idx_processing_job_session_id (session_id)
) COMMENT='处理作业表';

CREATE TABLE IF NOT EXISTS data_asset (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '数据资产主键ID',
    task_id BIGINT NOT NULL COMMENT '关联采集任务ID',
    session_id BIGINT NULL COMMENT '关联Session记录ID',
    source_type VARCHAR(32) NOT NULL COMMENT '资产来源类型',
    source_key VARCHAR(64) NULL COMMENT 'source键',
    asset_type VARCHAR(64) NOT NULL COMMENT '资产类型',
    display_name VARCHAR(255) NOT NULL COMMENT '展示名称',
    file_id BIGINT NULL COMMENT '关联文件ID',
    external_path VARCHAR(512) NULL COMMENT '外部路径',
    file_format VARCHAR(64) NULL COMMENT '文件格式',
    size_remark VARCHAR(128) NULL COMMENT '大小说明',
    description VARCHAR(512) NULL COMMENT '描述',
    operator_remark VARCHAR(512) NULL COMMENT '操作备注',
    produced_by_job_id BIGINT NULL COMMENT '来源处理作业ID',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    CONSTRAINT fk_data_asset_task FOREIGN KEY (task_id) REFERENCES acquisition_task(id),
    CONSTRAINT fk_data_asset_session FOREIGN KEY (session_id) REFERENCES collection_session(id),
    CONSTRAINT fk_data_asset_file FOREIGN KEY (file_id) REFERENCES data_file(id),
    INDEX idx_data_asset_session_id (session_id),
    INDEX idx_data_asset_source_key (source_key),
    INDEX idx_data_asset_asset_type (asset_type)
) COMMENT='数据资产表';

CREATE TABLE IF NOT EXISTS asset_lineage (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '资产血缘主键ID',
    task_id BIGINT NOT NULL COMMENT '关联采集任务ID',
    session_id BIGINT NULL COMMENT '关联Session记录ID',
    source_asset_id BIGINT NOT NULL COMMENT '源资产ID',
    target_asset_id BIGINT NOT NULL COMMENT '目标资产ID',
    job_id BIGINT NOT NULL COMMENT '关联处理作业ID',
    relation_type VARCHAR(64) NOT NULL COMMENT '关系类型',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    CONSTRAINT fk_asset_lineage_task FOREIGN KEY (task_id) REFERENCES acquisition_task(id),
    CONSTRAINT fk_asset_lineage_session FOREIGN KEY (session_id) REFERENCES collection_session(id),
    CONSTRAINT fk_asset_lineage_source_asset FOREIGN KEY (source_asset_id) REFERENCES data_asset(id),
    CONSTRAINT fk_asset_lineage_target_asset FOREIGN KEY (target_asset_id) REFERENCES data_asset(id),
    CONSTRAINT fk_asset_lineage_job FOREIGN KEY (job_id) REFERENCES processing_job(id),
    INDEX idx_asset_lineage_session_id (session_id)
) COMMENT='资产血缘表';

CREATE TABLE IF NOT EXISTS session_import_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Session导入记录主键ID',
    task_id BIGINT NOT NULL COMMENT '关联平台任务ID',
    session_record_id BIGINT NULL COMMENT '关联Session记录ID',
    collector_client_id BIGINT NULL COMMENT '关联采集端ID',
    local_task_id VARCHAR(64) NULL COMMENT '采集端本地任务ID',
    local_session_id VARCHAR(128) NOT NULL COMMENT '采集端本地Session ID',
    archive_file_id BIGINT NULL COMMENT '归档文件ID',
    status VARCHAR(32) NOT NULL COMMENT '导入状态',
    manifest_json TEXT NOT NULL COMMENT '原始manifest JSON',
    source_endpoint VARCHAR(32) NOT NULL COMMENT '导入来源接口',
    request_id VARCHAR(64) NULL COMMENT '请求追踪ID',
    message VARCHAR(512) NULL COMMENT '状态说明',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    CONSTRAINT fk_session_import_record_task FOREIGN KEY (task_id) REFERENCES acquisition_task(id),
    CONSTRAINT fk_session_import_record_session FOREIGN KEY (session_record_id) REFERENCES collection_session(id),
    CONSTRAINT fk_session_import_record_collector_client FOREIGN KEY (collector_client_id) REFERENCES collector_client(id),
    CONSTRAINT fk_session_import_record_archive_file FOREIGN KEY (archive_file_id) REFERENCES data_file(id),
    UNIQUE INDEX idx_session_import_local_session_id (local_session_id),
    INDEX idx_import_collector_client_id (collector_client_id),
    INDEX idx_import_task_request_id (task_id, request_id)
) COMMENT='Session导入记录表';
CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '用户主键ID',
    username VARCHAR(64) NOT NULL COMMENT '登录账号',
    password_hash VARCHAR(255) NOT NULL COMMENT '密码哈希',
    display_name VARCHAR(128) NOT NULL COMMENT '展示名称',
    role_code VARCHAR(32) NOT NULL COMMENT '角色编码',
    is_admin TINYINT NOT NULL DEFAULT 0 COMMENT '是否管理员',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '用户状态',
    phone VARCHAR(32) NULL COMMENT '手机号',
    email VARCHAR(128) NULL COMMENT '邮箱',
    remark VARCHAR(512) NULL COMMENT '备注',
    last_login_at DATETIME NULL COMMENT '最近登录时间',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    UNIQUE INDEX uk_sys_user_username (username),
    INDEX idx_sys_user_role_code (role_code),
    INDEX idx_sys_user_status (status)
) COMMENT='平台用户表';
